services:
    api:
        build:
            context: './api/vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './api:/var/www/html'
    
    app:
        build:
            context:    ./app
            dockerfile: docker/Dockerfile
            target:     development
        environment:
            NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        command:  sleep infinity
        ports:    [ "${APP_PORT}:${APP_PORT}" ]
        restart:  unless-stopped
        volumes:  [ ./app:/workspaces/app ]

    database:
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
