services:
    api:
        build:
            context: './api/vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './api:/var/www/html'
    
    app:
        build:
            context:    ./app
            dockerfile: docker/Dockerfile
            target:     runner
        args:
            # Variables required for the build
            NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

    database:
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
